### ISSUE TITLE
Is it possible to have arrays within arrays?

### ISSUE THREAD

**Issue by tinyweasel** [kellyselden/ember-array-helper#11]
I'm using this addon to render a datatable with this https://github.com/mfcollins3/ember-datatables addon, and some of the cells need to contain hasMany relationships. Is it possible to assign a property as in the following example to another array? For example could you have that property set to an array of employee names, which would come from a related employee model?

```
(hash title="Employees" property="employee.name")

{{data-table data=model
             columns=(array
               (hash title="Name" property="name")
               (hash title="Position" property="position")
               (hash title="Office" property="office")
               (hash title="Age" property="age")
               (hash title="Start date" property="startDate" render=(datetime-renderer "MMM D YYYY"))
               (hash title="Salary" property="salary")
             )}}
```

**Comment by kellyselden** [comment]
I'm not quite sure what you're trying to do in your example, but arrays within arrays should work:

```hbs
{{foo-bar
  arrays=(array
    (array "foo" "bar")
    (array "foo" "bar")
  )
}}
```

**Comment by tinyweasel** [comment]
I'm making a datatable. The model used is Person, and it has column headers Name, Position, Office, etc, which are attributes of the Person model. But I need the Employee column to contain a list of employee names, which come from the Employee model, which the Person hasMany of. So I'd need to assign the employee property in the datatable to an array of employee names. Is that possible?

**Comment by kellyselden** [comment]
Not sure. You might have to do some array mapping outside the scope of this addon.
